[package]
name = "chipmatch"
version = "0.2.0"
authors = ["Jan Christian Kaessens <j.kaessens@ikmb.uni-kiel.de>"]
description = "Tries to identify the chip type from a given BIM file"

[dependencies]
zip = "0.4"
clap = "2.32"

